fragment PageParts on Page {
  __typename
  title
  description
  hero {
    __typename
    title
    subtitle
    buttons {
      __typename
      text
      href
      style
    }
  }
  blocks {
    __typename
    ... on PageBlocksTextBlock {
      title
      content
      background
    }
    ... on PageBlocksStatsBlock {
      title
      subtitle
      stats {
        __typename
        number
        label
        description
      }
    }
    ... on PageBlocksFeatureGrid {
      title
      subtitle
      columns
      features {
        __typename
        title
        description
        icon
      }
    }
  }
}
