fragment Data_postParts on Data_post {
  __typename
  title
  date
  description
  body
}

fragment PagesParts on Pages {
  __typename
  title
  body
}

fragment Site_contentParts on Site_content {
  __typename
  title
  description
  body
}

fragment PostParts on Post {
  __typename
  title
  body
}
