backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'src/content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Hero Title', name: 'hero_title', widget: 'string' }
          - { label: 'Hero Description', name: 'hero_description', widget: 'text' }
          - { label: 'Hero Image', name: 'hero_image', widget: 'image' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
      - label: 'About Page'
        name: 'about'
        file: 'src/content/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
      - label: 'Products Page'
        name: 'products'
        file: 'src/content/products.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
      - label: 'Technology Page'
        name: 'technology'
        file: 'src/content/technology.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
      - label: 'Contact Page'
        name: 'contact'
        file: 'src/content/contact.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Address', name: 'address', widget: 'text' }
          - { label: 'Phone', name: 'phone', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
